In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
retail = pd.read_csv('retail_data.csv')

In [3]:
import pandas as pd
import numpy as np

# Assuming 'retail' is your DataFrame

# Drop duplicate rows
retail.drop_duplicates(inplace=True)

# Convert 'Date' column to datetime format
retail['Date'] = pd.to_datetime(retail['Date'], dayfirst=True)

# List of columns to exclude from replacement and conversion
exclude_columns = ['States/UTs', 'Date']

# Replace empty strings with NaN
retail.loc[:, ~retail.columns.isin(exclude_columns)] = retail.loc[:, ~retail.columns.isin(exclude_columns)].replace(' ', pd.NA)

# Convert columns to numeric, coercing errors to NaN
retail.loc[:, ~retail.columns.isin(exclude_columns)] = retail.loc[:, ~retail.columns.isin(exclude_columns)].apply(pd.to_numeric, errors='coerce')

# Optionally, fill NaN values with a default value if necessary
retail.loc[:, ~retail.columns.isin(exclude_columns)] = retail.loc[:, ~retail.columns.isin(exclude_columns)].fillna(0)

# Convert columns to float
retail.loc[:, ~retail.columns.isin(exclude_columns)] = retail.loc[:, ~retail.columns.isin(exclude_columns)].astype(float)

# Drop columns that contain only NaN values (which can be considered as "garbage columns")
retail.dropna(axis=1, how='all', inplace=True)

# Now your DataFrame should be cleaned and free of empty columns

ValueError: time data "Date" doesn't match format "%d-%m-%Y", at position 169. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df=df[df.columns[:24]]

In [ ]:
unique_states= df['States/UTs'].unique()

In [ ]:
unique_states=unique_states[4:]

In [ ]:
len(unique_states)

35

In [ ]:
datasets={}
for st in unique_states:
    date_df = df[df['States/UTs'] == st]
    datasets[st] = date_df

In [ ]:
datasets['Bihar']

,States/UTs,Rice,Wheat,Atta (Wheat),Gram Dal,Tur/Arhar Dal,Urad Dal,Moong Dal,Masoor Dal,Sugar,...,Soya Oil (Packed),Sunflower Oil (Packed),Palm Oil (Packed),Gur,Tea Loose,Salt Pack (Iodised),Potato,Onion,Tomato,Date
8,Bihar,37.63,26,32.5,67.31,105.81,100.38,98.06,89.19,43.19,...,154.88,186.82,135.85,46.63,278.81,19.75,21.31,23.25,40.94,30-08-2022
45,Bihar,37.63,26.19,32.75,66.63,105.63,100.44,99,89.69,43.38,...,152.56,187.36,136.69,46.56,278.13,19.94,21.63,23.19,40.56,31-08-2022
81,Bihar,37.47,26.29,32.47,67.12,105.59,100.59,99,90,43.24,...,153.94,187.83,136.79,46,282.94,19.94,21.47,23.24,39.76,01-09-2022
117,Bihar,37.41,26.24,32.41,67.47,105.47,100.47,98.88,89.82,43.35,...,153.94,187.83,135.93,46.06,283.59,20,21.47,23.18,39.12,02-09-2022
153,Bihar,36.73,26.07,32.27,67.4,104.87,100.07,98.8,89.6,43.33,...,153.47,185.73,135.17,46.27,286.93,20.47,21.27,22.2,39.07,03-09-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26197,Bihar,37.63,28.33,33.67,86.46,161.29,123.67,113.33,81.08,44.46,...,124.42,148.45,103.16,49,283.22,23.04,33.67,42.58,53,26-08-2024
26232,Bihar,37.86,28.14,33.89,85.57,158.7,121.32,113.59,80.35,44.38,...,126.27,148.8,105.45,47.97,277.75,23.11,33.27,42.43,53.54,27-08-2024
26270,Bihar,37.84,28.16,33.87,85.63,158.61,121.13,113.74,80.24,44.45,...,126,148.26,105.2,48.03,275.24,23.16,33.13,42.47,52.79,28-08-2024
26307,Bihar,37.92,28.14,33.95,85.7,158.41,121.14,113.84,80.27,44.47,...,126.16,148.53,105.48,48.03,276.29,23.39,33.22,42.62,51.84,29-08-2024
26345,Bihar,37.86,28.22,33.89,85.62,158.57,121.22,113.78,80.08,44.54,...,126.08,147,105.52,47.86,276.51,23.06,33.41,42.7,51.19,30-08-2024

In [ ]:
crops=df.columns.tolist()

In [ ]:
crops[1:-1]

['Rice',
 'Wheat',
 'Atta (Wheat)',
 'Gram Dal',
 'Tur/Arhar Dal',
 'Urad Dal',
 'Moong Dal',
 'Masoor Dal',
 'Sugar',
 'Milk @',
 'Groundnut Oil (Packed)',
 'Mustard Oil (Packed)',
 'Vanaspati (Packed)',
 'Soya Oil (Packed)',
 'Sunflower Oil (Packed)',
 'Palm Oil (Packed)',
 'Gur',
 'Tea Loose',
 'Salt Pack (Iodised)',
 'Potato',
 'Onion',
 'Tomato']

In [ ]:
dicto={}
for st in unique_states:
    cros={}
    for crop in crops:
        dfo=datasets[st][[crop,'Date']]
        cros[crop]=dfo
    dicto[st]=cros

In [ ]:
dicto['Bihar']['Rice']

        Rice        Date
8      37.63  30-08-2022
45     37.63  31-08-2022
81     37.47  01-09-2022
117    37.41  02-09-2022
153    36.73  03-09-2022
...      ...         ...
26197  37.63  26-08-2024
26232  37.86  27-08-2024
26270  37.84  28-08-2024
26307  37.92  29-08-2024
26345  37.86  30-08-2024

[732 rows x 2 columns]

In [ ]:
df